### PR TITLE
Account screen delete and add

### PR DESCRIPTION
**Pull request by Draakje10**

### CODE REVIEW

**Review by ronp2001 — CHANGES_REQUESTED** [review]
implemented functionality is decent. and bonus points for writing some tests

however the styling is not uniform with the rest of the application (see customer screen on latest dev branch and log screen on logs branch)

no pagination,
create new account screen:
- numerical input witouth any description? no idea what this is for
- checkbox witouth description? i am going to guess this means wants notification but how is the end user supposed to know this
- horizontal scrollbar?

**Comment by ronp2001** [comment]
image

also an image of a cardboard box when adding a new employee?

**Comment by ronp2001** [comment]
preferably also functionality to edit an already existing employee.

what if they switch to a different location say ROM1 -> ROM2
or their e-mail changes

**Review by DaaromThomas — APPROVED** [review]

**Review by ronp2001 — CHANGES_REQUESTED** [review]
lgtm except for one visual change

image


preferably make it look more like the customer table version then (except for the white text that can stay the same:

image

**Pull request merged**
